# =============================================================================
# Snakemake profile -- local execution
# =============================================================================
# Usage: snakemake --profile profiles/local --configfile config/config.yaml
# =============================================================================

cores: 64
keep-going: true
printshellcmds: true
rerun-incomplete: true
latency-wait: 30
